image:
- Ubuntu

stack: python 3

environment:
  PY_DIR: C:\Python36-x64

clone_depth: 3

before_build:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

- sh: sudo apt-get -yq update > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends ffmpeg > /dev/null

build_script:
- pip install -e .[tests]
  
after_build:
- pytest -sv

