image:
- Visual Studio 2017
- Ubuntu

stack: python 3

build: off

environment:
  PY_DIR: C:\Python37-x64

clone_depth: 3

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
- cmd: cinst -y ffmpeg

- sh: sudo apt-get -yq update > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends ffmpeg > /dev/null

install:
- pip install -e .[tests]
  
test_script:
- pytest -sv

