language: python
fast_finish: true

python:
  - 3.5
  - 3.6
  - "3.7-dev"

os:
  - linux

group: travis_latest

git:
  depth: 3

addons:
  apt:
    packages:
    - ffmpeg


install: pip -q install -e .[tests]

script: coverage run tests/Test.py -v

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7* ]]; then coveralls; fi

