language: generic
fast_finish: true
sudo: required

env:
  - TRAVIS_PYTHON_VERSION=3.6
  - TRAVIS_PYTHON_VERSION=3.7

os:
  - linux
  - osx

dist: xenial
group: travis_latest

git:
  depth: 3
  
addons:
  apt:
    packages: ffmpeg

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r

  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
    brew update > /dev/null;
    brew install ffmpeg > /dev/null;
    fi

install: pip -q install -e .[tests]

script:
  - pytest -sv
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

