language: python
fast_finish: true

python:
  - 3.5
  - 3.6

os:
  - linux

group: travis_latest

git:
  depth: 3


install: pip -q install -e .[tests]

script: 
  - pytest -v
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then coverage run tests/test_all.py -v; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then coveralls; fi

