language: python
fast_finish: true

python:
  - 3.5

os:
  - linux

dist: xenial
group: travis_latest

git:
  depth: 3

addons:
  apt:
    packages:
    - ffmpeg


install: pip -q install -e .[tests]

script: coverage run tests/Test.py -v

after_success: coveralls

