language: python
fast_finish: true

python:
  - 3.5
  - 3.6

os:
  - linux

group: travis_latest

git:
  depth: 3


install: pip -q install -e .[tests]

script: coverage run tests/Test.py -v

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then coveralls; fi

