language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

sudo: required
dist: trusty
group: edge
  

notifications:
  email: false

git:
  depth: 3

before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt install ffmpeg
  - pip -q install coveralls

install: pip -q install -e .

script: coverage run tests/test.py -v

after_success: coveralls

