language: python
fast_finish: true

python:
  - 3.5

os:
  - linux

group: travis_latest

git:
  depth: 3
  
addons:
  apt:
    packages:
    - libav-tools


install: pip -q install -e .[tests]

script: coverage run tests/Test.py -v

after_success: coveralls

