name: ci

on:
  push:
    paths:
    - "**.py"
    - .github/workflows/ci.yml

jobs:

  linux_py36:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - run: pip install .[tests]

    - name: install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ffmpeg

    - run: pytest


  linux_py3x:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy . src

    - name: install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ffmpeg

    - run: pytest


  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install .[tests]

    - run: brew install ffmpeg

    - run: pytest

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install .[tests]

    - run: cinst -y ffmpeg

    - run: pytest
