name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
    - "**.py"
    - .github/workflows/ci.yml

jobs:

  core:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.9', '3.10', '3.11']
        include:
        - python-version: '3.x'
          os: macos-latest
        - python-version: '3.x'
          os: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - name: install prereqs (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install --no-install-recommends ffmpeg

    - name: install prereqs (macOS)
      if : runner.os == 'macOS'
      run: brew install ffmpeg

    - name: install prereqs (Windows)
      if: runner.os == 'Windows'
      run: cinst -y ffmpeg

    - run: pytest
